### ISSUE TITLE
Accidentally adding additional stage to max stage taxon

### ISSUE THREAD

**Issue by ltaylor2** [ltaylor2/finalproject#1]
https://github.com/ltaylor2/finalproject/blob/488388a2c0cd20834aa88377272c7336ab7db5dc/Scripts/wrangle_plumages.r#L31

**Comment by lemellenthin** [comment]
Was this resolved? If not, could you provide the error/problem?

**Comment by ltaylor2** [comment]
Pushed the fix. TY!
