### ISSUE TITLE
Revamp character coding

### ISSUE THREAD

**Issue by ltaylor2** [ltaylor2/finalproject#2]
https://github.com/ltaylor2/finalproject/blob/6269ce5bbb6f07575ec27926bae7606715eadd00/Data/plumage_all.nex#L9

Explicitly code STAGES as characters, along with

This reintroduces the tripartite plumage patch dependency:

DPM is dependent on dichromatism: P1 | D (i.e., dichromatism)
Inserted stages are dependent on earlier inserted stages: P2 | P1 for example
Predefinitive plumage characters are dependent on plumage stages: P1-Crown | P1

And, to add a color-type dependency:
P1-Crown-Structural | P1-Crown
P1-Crown-Carotenoid | P1-Crown
P1-Crown-Melanin | P1-Crown

This change to character coding will allow the explicit detection of P-STAGE and P-CHARACTER homologies, as well as the separate transition rates for STAGE changes versus CHARACTER changes versus COLOR changes. Need then PARAMO dependency.

**Comment by caseywdunn** [comment]
Great to see you using issues to specify explicit incremental goals.
